development:
  adapter: postgresql
  encoding: unicode
  database: echo_twitter_dev
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: echo_twitter_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: echo_twitter_prod
  username: postgres
  password: postgres
  host: localhost
